# Ejercicio día 8
**Programación I**

## Ejercicio 1

Cree una matriz que contenga ceros. Rellene la mitad de ellos aleatoriamente con unos.

In [119]:
import numpy as np

In [2]:
np.__version__

'1.16.5'

In [57]:
a = np.zeros([4,4])#Creo una matriz de ceros
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [58]:
b = a.flatten()#Convierto la matriz en una especie de vector fila o lista
b

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [59]:
b[:8]=1 #Pido que de ese vector fila, exactamente la mitad de sus elementos sean unos exactamente. 
b

array([1., 1., 1., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0.])

In [60]:
np.random.shuffle(b) #Por medio de shuffle pido que mezcle de forma aleatoria mezcle el vector fila o lista 
b

array([1., 0., 0., 1., 1., 1., 0., 0., 0., 0., 1., 0., 0., 1., 1., 1.])

In [61]:
bb= b.reshape(4,4)#Por último pido que reestructure ese vector fila en una matriz como la original de las mismas
#dimensiones
bb

array([[1., 0., 0., 1.],
       [1., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 1., 1., 1.]])

In [ ]:
#Forma 2 

In [105]:
f=4
c=4
x=np.zeros([f*c])
x

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [106]:
y=np.arange(16)
y

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [107]:
z=np.random.choice(y, int(f*c/2), replace=False)
z

array([ 6,  3, 15, 10,  1,  8, 14, 12])

In [108]:
x[z]=1

In [110]:
x.resize(f,c)
x

array([[0., 1., 0., 1.],
       [0., 0., 1., 0.],
       [1., 0., 1., 0.],
       [1., 0., 1., 1.]])

## Ejercicio 2
Cree dos matrices de dimensiones $(5,2)$. La primera rellena de ceros y la siguiente de unos. 
1.	Convierta las matrices en vectores columna. 
2.	Apile ambos vectores a lo largo de una tercera dimensión. 
3.	Con las matrices originales, conviértalas en vectores fila y concaténelos verticalmente. 



In [12]:
a = np.zeros([5, 2])
a

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [19]:
b = np.ones([5, 2])
b

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

#Incisio 1 


In [23]:
vc1=a.flatten()
vc1

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [31]:
c1=vc1[:,None]
c1

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.]])

In [27]:
vc2=b.flatten()
vc2

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [29]:
c2=vc2[:,None]
c2

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.]])

#Inciso 2

In [43]:
dimension = np.dstack((c1, c2))
dimension

array([[[0., 1.]],

       [[0., 1.]],

       [[0., 1.]],

       [[0., 1.]],

       [[0., 1.]],

       [[0., 1.]],

       [[0., 1.]],

       [[0., 1.]],

       [[0., 1.]],

       [[0., 1.]]])

In [33]:
c1[:, np.newaxis, np.newaxis]

array([[[[0.]]],


       [[[0.]]],


       [[[0.]]],


       [[[0.]]],


       [[[0.]]],


       [[[0.]]],


       [[[0.]]],


       [[[0.]]],


       [[[0.]]],


       [[[0.]]]])

#Inciso 3 

In [30]:
np.concatenate((vc1[:,None],vc2[:,None]), axis=0)

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.]])

## Ejercicio 3

Dada la función $f(x,y,z) = 2x +3y + z^2$
1.	Genere una matriz con números aleatorios para cada variable. 
2.	Evalúe la matriz anterior en la función. El resultado debe ser una matriz. 

In [4]:
#Inciso 1
matrix = np.random.randint(3, size=(10,3))
matrix

array([[0, 2, 2],
       [1, 1, 1],
       [0, 0, 2],
       [2, 0, 0],
       [2, 1, 1],
       [2, 2, 2],
       [0, 0, 2],
       [2, 1, 0],
       [1, 1, 2],
       [0, 0, 1]])

In [5]:
def f(matrix):
    return 2*(matrix[:,0]) + 3*(matrix[:,1]) + (matrix[:,2])**2

In [6]:
a=f(matrix)
a

array([10,  6,  4,  4,  8, 14,  4,  7,  9,  1])

In [7]:
np.hsplit(a,10)

[array([10]),
 array([6]),
 array([4]),
 array([4]),
 array([8]),
 array([14]),
 array([4]),
 array([7]),
 array([9]),
 array([1])]

In [8]:
aa= a.reshape(10,1)
aa

array([[10],
       [ 6],
       [ 4],
       [ 4],
       [ 8],
       [14],
       [ 4],
       [ 7],
       [ 9],
       [ 1]])

In [11]:
a.flatten()
c=a[:,None]
c

array([[10],
       [ 6],
       [ 4],
       [ 4],
       [ 8],
       [14],
       [ 4],
       [ 7],
       [ 9],
       [ 1]])

## Ejercicio 4

Suponga que dentro de un cuadrado de lado 50 cm, hay un cuadrado de 20cm. Ambos cuadrados comparten centro. Estime el área del cuadrado interno por método Monte Carlo. [Consulte Aquí]( http://mathonweb.com/entrtain/monte/t_monte.htm)

In [87]:
sq = np.random.randint(0,2,([50,50])) #Se crea un cuadrado de dimensión de 50*50 con 0 y 1 aleatorios 
sq

array([[1, 1, 0, ..., 0, 0, 1],
       [0, 1, 1, ..., 0, 1, 0],
       [1, 1, 1, ..., 0, 0, 1],
       ...,
       [0, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 0, 0],
       [1, 1, 1, ..., 0, 1, 0]])

In [88]:
sq2 = sq[0:21,0:21] #se extrae el cuadrado de la esquina del cuadrado de 50*50
sq2

array([[1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1],
       [0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0],
       [1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0],
       [0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1],
       [0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0],
       [1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0],
       [0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0],
       [0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1],
       [0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0],
       [0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1],
       [0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0],
       [1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0],
       [1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0,

In [89]:
area_sq=sum(sq.flatten()) #La suma de los 1 será equivalente al área del cuadrado de 50*50
area_sq

1256

In [90]:
area_sq2 = sum (sq2.flatten()) #La suma de los 1 será equivalente al área del cuadrado interior en la esquina
area_sq2

222

In [91]:
proportion = area_sq2/area_sq #se calcula la proporción entre el cuadrado pequeño y el cuadrado grande 
proportion

0.1767515923566879

In [92]:
Estimation_Area= proportion *2500 #Esa proporción multiplicada por el área actual del cuadrado de 50*50 da un número
#cercano al área del cuadrado interno que sería de 400
Estimation_Area

441.8789808917197

In [ ]:
#Cuadrado centrado 

In [111]:
cua = np.random.randint(0,2,([50,50])) #Se crea un cuadrado de dimensión de 50*50 con 0 y 1 aleatorios 
cua

array([[1, 1, 0, ..., 0, 1, 0],
       [0, 0, 1, ..., 0, 1, 1],
       [1, 1, 0, ..., 0, 0, 0],
       ...,
       [1, 0, 0, ..., 1, 1, 1],
       [0, 1, 1, ..., 1, 0, 0],
       [0, 1, 1, ..., 0, 1, 1]])

In [112]:
cua2 = cua[20:40,20:40] #se extrae el cuadrado de en medio del cuadrado de 50*50
cua2

array([[0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1],
       [0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1],
       [0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1],
       [1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1],
       [0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1],
       [1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1],
       [1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0],
       [0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1],
       [0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1],
       [0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0],
       [1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0],
       [1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0],
       [0, 1, 0, 0, 0, 1, 1, 1, 1,

In [113]:
area_cua=sum(cua.flatten()) #La suma de los 1 será equivalente al área del cuadrado de 50*50
area_cua

1272

In [114]:
area_cua2 = sum (cua2.flatten()) #La suma de los 1 será equivalente al área del cuadrado interior en el medio
area_cua2

219

In [115]:
propo = area_cua2/area_cua #se calcula la proporción entre el cuadrado pequeño y el cuadrado grande 
propo

0.1721698113207547

In [116]:
Estimacion= propo *2500 #Esa proporción multiplicada por el área actual del cuadrado de 50*50 da un número
#cercano al área del cuadrado interno que sería de 400
Estimacion

430.42452830188677

***
# *Tarea*

1. De las siguientes secciones, escoger 73 funciones de NumPy y mostrar su utilización en un ejemplo.

    - [Array creation routines](https://numpy.org/devdocs/reference/routines.array-creation.html)

    - [Array manipulation routines](https://numpy.org/devdocs/reference/routines.array-manipulation.html)

    - [Binary operations](https://numpy.org/devdocs/reference/routines.bitwise.html)

    - [String operations](https://numpy.org/devdocs/reference/routines.char.html)
    

2. Crear un ejemplo de cómo guardar y cargar arreglos de un archivo binario `.npy` y `.npz`:

    - [NumPy binary files (NPY, NPZ)](https://numpy.org/devdocs/reference/routines.io.html#numpy-binary-files-npy-npz)
    
3. Crear un ejemplo de cómo guardar y cargar arreglos de un archivo de texto `.txt`:

    - [NumPy Text files](https://numpy.org/devdocs/reference/routines.io.html#text-files)    
    
4. Crear una función llamada `estimacionMCO` que lea un archivo CSV con 7 columnas, que corresponden a las variables $(x_{1i}, \ldots, x_{6i})$ y $y_i$. 
    - La función debe computar matricialmente los parámetros del modelo de regresión lineal: $y = X\beta$. 
    - Estos parámetros deben ser devueltos como un arreglo de NumPy. 

    - Utilice la función de lectura de archivos de NumPy.

73 funciones

ONES AND ZEROS 

#1
numpy.empty(shape, dtype=float, order='C')
 
Return a new array of given shape and type, without initializing entries

In [131]:
a=np.empty(2, dtype=int, order='C')
a

array([1964933376,        372])

#2
numpy.empty_like(prototype, dtype=None, order='K', subok=True, shape=None)
Return a new array with the same shape and type as a given array.


In [132]:
a = ([2,4])
np.empty_like(a)

array([         0, 1072693248])

#3
numpy.eye(N, M=None, k=0, dtype=<class 'float'>, order='C')
Return a 2-D array with ones on the diagonal and zeros elsewhere.

In [133]:
np.eye(4, dtype=int)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

#4
numpy.identity(n, dtype=None)
Return the identity array.


In [134]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

#5
numpy.ones(shape, dtype=None, order='C')
Return a new array of given shape and type, filled with ones.

In [135]:
np.ones((2,1), dtype=int, order='C')

array([[1],
       [1]])

#6
numpy.ones_like(a, dtype=None, order='K', subok=True, shape=None)
Return an array of ones with the same shape and type as a given array.


In [138]:
x = np.arange(12)
x = x.reshape((2, 6))
x

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [139]:
np.ones_like(x)

array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]])

#7
numpy.zeros(shape, dtype=float, order='C')
Return a new array of given shape and type, filled with zeros.


In [140]:
np.zeros((5,5), dtype=int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

#8
numpy.zeros_like(a, dtype=None, order='K', subok=True, shape=None)
Return an array of zeros with the same shape and type as a given array.


In [141]:
x = np.arange(12)
x = x.reshape((2, 6))
x

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [142]:
np.zeros_like(x)

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

#9
numpy.full(shape, fill_value, dtype=None, order='C')
Return a new array of given shape and type, filled with fill_value.


In [144]:
np.full((4, 4), 100)


array([[100, 100, 100, 100],
       [100, 100, 100, 100],
       [100, 100, 100, 100],
       [100, 100, 100, 100]])

#10
numpy.full_like(a, fill_value, dtype=None, order='K', subok=True, shape=None)
Return a full array with the same shape and type as a given array.


In [147]:
x = np.arange(10, dtype=int)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [148]:
np.full_like(x, 1)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

FROM EXISTING DATA

#11 
numpy.array(object, dtype=None, copy=True, order='K', subok=False, ndmin=0)
Create an array.


In [150]:
np.array(np.mat('0 1; 1 0'))

array([[0, 1],
       [1, 0]])

#12
numpy.asarray(a, dtype=None, order=None)
Convert the input to an array.


In [151]:
x = [4, 2]
np.asarray(x)

array([4, 2])

#13
numpy.asanyarray(a, dtype=None, order=None)[source]¶
Convert the input to an ndarray, but pass ndarray subclasses through.


In [152]:
x = [1, 2]
np.asanyarray(x)

array([1, 2])

#14
numpy.ascontiguousarray(a, dtype=None)
Return a contiguous array (ndim >= 1) in memory (C order).


In [156]:
x = np.arange(6)
x

array([0, 1, 2, 3, 4, 5])

In [162]:
np.ascontiguousarray(x)

array([0, 1, 2, 3, 4, 5])

#15
numpy.asmatrix(data, dtype=None)
Interpret the input as a matrix.


In [167]:
x = np.array(2)
x

array(2)

In [168]:
m = np.asmatrix(x)
m

matrix([[2]])

#16
numpy.copy(a, order='K')
Return an array copy of the given object.


In [170]:
x = np.array([1, 1, 1])
y = x
z = np.copy(x)

In [173]:
z

array([1, 1, 1])

In [171]:
x[0] = 10
x[0] == y[0]

True

In [174]:
x

array([10,  1,  1])

In [175]:
y

array([10,  1,  1])

In [176]:
z

array([1, 1, 1])

In [172]:
x[0] == z[0]

False

#17
numpy.frombuffer(buffer, dtype=float, count=-1, offset=0)
Interpret a buffer as a 1-dimensional array.

In [186]:
np.frombuffer(b'\x03\x05',dtype=np.uint8)

array([3, 5], dtype=uint8)

#18
numpy.fromstring(string, dtype=float, count=-1, sep='')
A new 1-D array initialized from text data in a string.


In [192]:
np.fromstring('4 2', dtype=int, sep=' ')

array([4, 2])

In [193]:
x1=np.array([1,2,3,4])
x2=np.array(['a','dd','xyz','12'])
x3=np.array([1.1,2,3,4])
r = np.core.records.fromarrays([x1,x2,x3],names='a,b,c')
print(r[1])

(2, 'dd', 2.)


#19
numpy.core.records.fromrecords(recList, dtype=None, shape=None, formats=None, names=None, titles=None, aligned=False, byteorder=None)
create a recarray from a list of records in text form


In [196]:
r=np.core.records.fromrecords([(456,'dbe',1.2),(275,'def',1.5)],
names='col1,col2,col3')
print(r[1])

(275, 'def', 1.5)


#20
numpy.arange([start, ]stop, [step, ]dtype=None)
Return evenly spaced values within a given interval.


In [197]:
np.arange(3,7,2)

array([3, 5])

#21
numpy.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)
Return evenly spaced numbers over a specified interval.

In [199]:
np.linspace(1.0, 2.0, num=5)

array([1.  , 1.25, 1.5 , 1.75, 2.  ])

#22
numpy.logspace(start, stop, num=50, endpoint=True, base=10.0, dtype=None, axis=0)
Return numbers spaced evenly on a log scale.


In [200]:
np.logspace(1.0, 2.0, num=4)

array([ 10.        ,  21.5443469 ,  46.41588834, 100.        ])

#23
numpy.geomspace(start, stop, num=50, endpoint=True, dtype=None, axis=0)
Return numbers spaced evenly on a log scale (a geometric progression).

In [201]:
np.geomspace(1, 1000, num=4)

array([   1.,   10.,  100., 1000.])

#24
numpy.mgrid = <numpy.lib.index_tricks.MGridClass object>
nd_grid instance which returns a dense multi-dimensional “meshgrid”.


In [209]:
np.mgrid[0:4,0:4,0:4]

array([[[[0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0]],

        [[1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1]],

        [[2, 2, 2, 2],
         [2, 2, 2, 2],
         [2, 2, 2, 2],
         [2, 2, 2, 2]],

        [[3, 3, 3, 3],
         [3, 3, 3, 3],
         [3, 3, 3, 3],
         [3, 3, 3, 3]]],


       [[[0, 0, 0, 0],
         [1, 1, 1, 1],
         [2, 2, 2, 2],
         [3, 3, 3, 3]],

        [[0, 0, 0, 0],
         [1, 1, 1, 1],
         [2, 2, 2, 2],
         [3, 3, 3, 3]],

        [[0, 0, 0, 0],
         [1, 1, 1, 1],
         [2, 2, 2, 2],
         [3, 3, 3, 3]],

        [[0, 0, 0, 0],
         [1, 1, 1, 1],
         [2, 2, 2, 2],
         [3, 3, 3, 3]]],


       [[[0, 1, 2, 3],
         [0, 1, 2, 3],
         [0, 1, 2, 3],
         [0, 1, 2, 3]],

        [[0, 1, 2, 3],
         [0, 1, 2, 3],
         [0, 1, 2, 3],
         [0, 1, 2, 3]],

        [[0, 1, 2, 3],
         [0, 1, 2, 3],
         [

#25
numpy.diag(v, k=0)
Extract a diagonal or construct a diagonal array. 

In [ ]:
#Me devuelve la diagonal de la matriz creada. 

In [210]:
x = np.arange(9).reshape((3,3))
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [211]:
np.diag(x)

array([0, 4, 8])

#26
numpy.diagflat(v, k=0)
Create a two-dimensional array with the flattened input as a diagonal.

In [ ]:
#Se crea una matriz en el que el input se vuelve la diagonal de la matriz creada. 

In [212]:
np.diagflat([[1,2], [3,4]])

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

#27
numpy.tri(N, M=None, k=0, dtype=<class 'float'>)
An array with ones at and below the given diagonal and zeros elsewhere.


In [227]:
np.tri(3, 3,k=-1, dtype=int)

array([[0, 0, 0],
       [1, 0, 0],
       [1, 1, 0]])

#28
numpy.tril(m, k=0)
Lower triangle of an array.

In [232]:
x=([1,2,3],[4,5,6],[7,8,9])
y=np.asarray(x)
y

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [233]:
np.tril(y)

array([[1, 0, 0],
       [4, 5, 0],
       [7, 8, 9]])

#29
numpy.triu(m, k=0)
Upper triangle of an array.


In [234]:
x=([1,2,3],[4,5,6],[7,8,9])
y=np.asarray(x)
y

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [235]:
np.triu(y)

array([[1, 2, 3],
       [0, 5, 6],
       [0, 0, 9]])

#30
numpy.mat(data, dtype=None)[source]¶
Interpret the input as a matrix

In [243]:
np.mat([[1, 2], [3, 4]])

matrix([[1, 2],
        [3, 4]])

#31
numpy.shape(a)
Return the shape of an array.


In [246]:
x=np.eye(3)
x


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [248]:
np.shape(x)

(3, 3)

#32
numpy.reshape(a, newshape, order='C')
Gives a new shape to an array without changing its data.


In [251]:
a = np.arange(9)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [252]:
a.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#33
numpy.ravel(a, order='C')
Return a contiguous flattened array.


In [254]:
x = np.array([[1, 0, 0], [0, 1, 0],[0,0,1]])
x

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [255]:
np.ravel(x)

array([1, 0, 0, 0, 1, 0, 0, 0, 1])

#34
numpy.atleast_2d(*arys)
View inputs as arrays with at least two dimensions.


In [256]:
np.atleast_2d(3)

array([[3]])

#35
numpy.atleast_1d(*arys)
Convert inputs to arrays with at least one dimension.


In [259]:
np.atleast_1d((3))

array([3])

#36
numpy.atleast_3d(*arys)
View inputs as arrays with at least three dimensions.


In [260]:
np.atleast_3d((3))

array([[[3]]])

#37
numpy.asscalar(a)
Convert an array of size 1 to its scalar equivalent.


In [262]:
np.asscalar(np.array([42]))

42

#38
numpy.concatenate((a1, a2, ...), axis=0, out=None)
Join a sequence of arrays along an existing axis.


In [264]:
a = np.array([[1, 2], [3, 4]])
a

array([[1, 2],
       [3, 4]])

In [265]:
b = np.array([[5, 6]])
b

array([[5, 6]])

In [266]:
np.concatenate((a, b), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

#39
numpy.stack(arrays, axis=0, out=None)
Join a sequence of arrays along a new axis.

In [270]:
a = np.array([1, 1, 1])
a

array([1, 1, 1])

In [271]:
b = np.array([1, 1, 1])
b

array([1, 1, 1])

In [272]:
np.stack((a, b))

array([[1, 1, 1],
       [1, 1, 1]])

#40
numpy.column_stack(tup)
Stack 1-D arrays as columns into a 2-D array.

In [273]:
a = np.array((1,2,3))
a

array([1, 2, 3])

In [274]:
b = np.array((5,6,7))
b

array([5, 6, 7])

In [275]:
np.column_stack((a,b))

array([[1, 5],
       [2, 6],
       [3, 7]])

#41
numpy.dstack(tup)
Stack arrays in sequence depth wise (along third axis).


In [276]:
a = np.array((1,2,3))
b = np.array((5,6,7))
np.dstack((a,b))

array([[[1, 5],
        [2, 6],
        [3, 7]]])

#42
numpy.hstack(tup)
Stack arrays in sequence horizontally (column wise).


In [277]:
a = np.array((1,2,3))
b = np.array((4,5,6))
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6])

#43
numpy.vstack(tup)
Stack arrays in sequence vertically (row wise).


In [278]:
a = np.array([1, 2, 3])
b = np.array([5, 6, 7])
np.vstack((a,b))

array([[1, 2, 3],
       [5, 6, 7]])

#44
numpy.split(ary, indices_or_sections, axis=0)
Split an array into multiple sub-arrays as views into ary.


In [281]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [283]:
np.split(x, 5)

[array([0, 1]), array([2, 3]), array([4, 5]), array([6, 7]), array([8, 9])]

#45
numpy.array_split(ary, indices_or_sections, axis=0)
Split an array into multiple sub-arrays.

In [289]:
x = np.arange(8)
x

array([0, 1, 2, 3, 4, 5, 6, 7])

In [290]:
np.array_split(x, 3)

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7])]

#46
numpy.dsplit(ary, indices_or_sections)
Split array into multiple sub-arrays along the 3rd axis (depth).

In [291]:
x = np.arange(16.0).reshape(2, 2, 4)
x

array([[[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.]],

       [[ 8.,  9., 10., 11.],
        [12., 13., 14., 15.]]])

In [292]:
np.dsplit(x, 2)

[array([[[ 0.,  1.],
         [ 4.,  5.]],
 
        [[ 8.,  9.],
         [12., 13.]]]), array([[[ 2.,  3.],
         [ 6.,  7.]],
 
        [[10., 11.],
         [14., 15.]]])]

#47
numpy.hsplit(ary, indices_or_sections)
Split an array into multiple sub-arrays horizontally (column-wise).

In [293]:
x = np.arange(16.0).reshape(2, 2, 4)
x

array([[[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.]],

       [[ 8.,  9., 10., 11.],
        [12., 13., 14., 15.]]])

In [294]:
np.hsplit(x, 2)

[array([[[ 0.,  1.,  2.,  3.]],
 
        [[ 8.,  9., 10., 11.]]]), array([[[ 4.,  5.,  6.,  7.]],
 
        [[12., 13., 14., 15.]]])]

#48
numpy.vsplit(ary, indices_or_sections)
Split an array into multiple sub-arrays vertically (row-wise).

In [297]:
x = np.arange(16.0).reshape(4, 4)
x

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.],
       [12., 13., 14., 15.]])

In [298]:
np.vsplit(x, 2)

[array([[0., 1., 2., 3.],
        [4., 5., 6., 7.]]), array([[ 8.,  9., 10., 11.],
        [12., 13., 14., 15.]])]

#49
numpy.tile(A, reps)
Construct an array by repeating A the number of times given by reps.

In [302]:
c = np.array([1,2,3,4])
c

array([1, 2, 3, 4])

In [303]:
np.tile(c,(4,3))

array([[1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4],
       [1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4],
       [1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4],
       [1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4]])

#50
numpy.repeat(a, repeats, axis=None)
Repeat elements of an array.

In [305]:
np.repeat(100, 4)

array([100, 100, 100, 100])

#51
numpy.delete(arr, obj, axis=None)
Return a new array with sub-arrays along an axis deleted. For a one dimensional array, this returns those entries not returned by arr[obj].


In [308]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [309]:
np.delete(a, 2, 0)

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

#52
numpy.unique(ar, return_index=False, return_inverse=False, return_counts=False, axis=None)
Find the unique elements of an array.

In [310]:
np.unique([1, 1, 2, 2, 3, 3])

array([1, 2, 3])

#53
numpy.flip(m, axis=None)
Reverse the order of elements in an array along the given axis.

In [311]:
A = np.arange(8).reshape((2,2,2))
A

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [312]:
np.flip(A, 0)

array([[[4, 5],
        [6, 7]],

       [[0, 1],
        [2, 3]]])

#54
numpy.fliplr(m)
Flip array in the left/right direction.

In [316]:
x = np.diag([1,2,3])
x

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [317]:
np.fliplr(x)

array([[0, 0, 1],
       [0, 2, 0],
       [3, 0, 0]])

#55
numpy.flipud(m)
Flip array in the up/down direction.

In [318]:
np.flipud(x)

array([[0, 0, 3],
       [0, 2, 0],
       [1, 0, 0]])

#56
numpy.reshape(a, newshape, order='C')
Gives a new shape to an array without changing its data.

In [319]:
a = np.array([[1,2,3], [4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [320]:
np.reshape(a, 6)

array([1, 2, 3, 4, 5, 6])

#57
numpy.roll(a, shift, axis=None)
Roll array elements along a given axis.

In [321]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [322]:
np.roll(x, 2)

array([8, 9, 0, 1, 2, 3, 4, 5, 6, 7])

#58
numpy.rot90(m, k=1, axes=(0, 1))
Rotate an array by 90 degrees in the plane specified by axes.

In [323]:
x = np.array([[1,2],[3,4]], int)
x

array([[1, 2],
       [3, 4]])

In [325]:
np.rot90(x)

array([[2, 4],
       [1, 3]])

#59
numpy.binary_repr(num, width=None)
Return the binary representation of the input number as a string.

In [327]:
np.binary_repr(4)

'100'

#60
numpy.char.add(x1, x2)
Return element-wise string concatenation for two arrays of str or unicode.

In [329]:
np.char.add("ho","la")

array('hola', dtype='<U4')

#61
numpy.char.multiply(a, i)
Return (a * i), that is string multiple concatenation, element-wise.

In [334]:
np.char.multiply("5",4)

array('5555', dtype='<U4')

#62
numpy.char.capitalize(a)
Return a copy of a with only the first character of each element capitalized.

In [340]:
c = np.array(['a1b2','cb2a','b2a1','da1b']) 
c

array(['a1b2', 'cb2a', 'b2a1', 'da1b'], dtype='<U4')

In [341]:
np.char.capitalize(c)

array(['A1b2', 'Cb2a', 'B2a1', 'Da1b'], dtype='<U4')

#63
numpy.char.lower(a)
Return an array with the elements converted to lowercase.

In [342]:
c = np.array(['ABCD','EFGH','IJKL','MNOP']) 
c

array(['ABCD', 'EFGH', 'IJKL', 'MNOP'], dtype='<U4')

In [343]:
np.char.lower(c)

array(['abcd', 'efgh', 'ijkl', 'mnop'], dtype='<U4')

#64
numpy.char.swapcase(a)
Return element-wise a copy of the string with uppercase characters converted to lowercase and vice versa.

In [345]:
c=np.array(['a1B c','1b Ca','b Ca1','cA1b'])
c

array(['a1B c', '1b Ca', 'b Ca1', 'cA1b'], dtype='<U5')

In [346]:
np.char.swapcase(c)

array(['A1b C', '1B cA', 'B cA1', 'Ca1B'], dtype='<U5')

#65
numpy.char.upper(a)
Return an array with the elements converted to uppercase.

In [347]:
c = np.array(['a1b c', '1bca', 'bca1'])
c

array(['a1b c', '1bca', 'bca1'], dtype='<U5')

In [348]:
np.char.upper(c)

array(['A1B C', '1BCA', 'BCA1'], dtype='<U5')

#66
numpy.char.compare_chararrays(a, b, cmp_op, rstrip)
Performs element-wise comparison of two string arrays using the comparison operator specified by cmp_op.

In [349]:
a = np.array(["a", "b", "cde"])
b = np.array(["a", "a", "dec"])
np.compare_chararrays(a, b, ">", True)

array([False,  True, False])

#67
numpy.char.zfill(a, width)
Return the numeric string left-filled with zeros


In [350]:
a="1"
a

'1'

In [351]:
np.char.zfill(a,4)

array('0001', dtype='<U4')

#68
numpy.char.isnumeric(a)
For each element, return True if there are only numeric characters in the element.

In [360]:
a="123456789"
a

'123456789'

In [361]:
np.char.isnumeric(a)

array(True)

#69
numpy.char.isdigit(a)
Returns true for each element if all characters in the string are digits and there is at least one character, false otherwise.


In [362]:
a="123456789"
a

'123456789'

In [363]:
np.char.isdigit(a)

array(True)

#70
numpy.char.lstrip(a, chars=None)
For each element in a, return a copy with the leading characters removed.


In [365]:
a=np.array(["bueno","bondad","bus"])
np.char.lstrip(a,"b")

array(['ueno', 'ondad', 'us'], dtype='<U6')

#71
numpy.trim_zeros(filt, trim='fb')
Trim the leading and/or trailing zeros from a 1-D array or sequence.

In [366]:
np.trim_zeros([0,0,0,0,0,0,0,0,0,0,0,0,2])

[2]

#72
numpy.expand_dims(a, axis)
Expand the shape of an array.

In [367]:
d=np.array([2,2])
d

array([2, 2])

In [369]:
dd=np.expand_dims(d, axis=0)
dd

array([[2, 2]])

#73
ndarray.T
The transposed array.


In [370]:
x = np.array([[1,2],[3,4]])
x

array([[1, 2],
       [3, 4]])

In [371]:
x.T

array([[1, 3],
       [2, 4]])

2. Crear un ejemplo de cómo guardar y cargar arreglos de un archivo binario `.npy` y `.npz`:

    - [NumPy binary files (NPY, NPZ)](https://numpy.org/devdocs/reference/routines.io.html#numpy-binary-files-npy-npz)

In [386]:
x=np.array([2,4,6,8])
np.save("binario.npy",x)

In [387]:
y=np.load("binario.npy")

In [388]:
y

array([2, 4, 6, 8])

In [400]:
a=np.array([2,4,6,8])
b=np.array([1,2])

In [401]:
np.savez('binario.npz', a=a, b=b)

In [402]:
c=np.load('binario.npz')

In [403]:
c["b"]

array([1, 2])

In [404]:
c["a"]

array([2, 4, 6, 8])

3. Crear un ejemplo de cómo guardar y cargar arreglos de un archivo de texto `.txt`:

    - [NumPy Text files](https://numpy.org/devdocs/reference/routines.io.html#text-files)   

In [379]:
x=np.array([1,2,3,4])
np.savetxt('texto1.txt',x,fmt='%f')
y=np.loadtxt('texto1.txt', dtype=float)

In [380]:
x

array([1, 2, 3, 4])

In [381]:
y

array([1., 2., 3., 4.])

In [382]:
z=np.loadtxt('prueba.txt', dtype=float)

In [383]:
z

array([5., 6., 7., 8.])

4. Crear una función llamada `estimacionMCO` que lea un archivo CSV con 7 columnas, que corresponden a las variables $(x_{1i}, \ldots, x_{6i})$ y $y_i$. 
    - La función debe computar matricialmente los parámetros del modelo de regresión lineal: $y = X\beta$. 
    - Estos parámetros deben ser devueltos como un arreglo de NumPy. 

    - Utilice la función de lectura de archivos de NumPy.

In [407]:
matrix = np.random.randint(10, size=(10,7))
matrix

array([[8, 2, 1, 8, 4, 2, 7],
       [1, 5, 4, 1, 0, 8, 1],
       [7, 7, 7, 5, 5, 7, 0],
       [2, 5, 1, 4, 5, 6, 5],
       [4, 4, 0, 9, 3, 4, 7],
       [1, 8, 7, 5, 9, 7, 8],
       [6, 3, 0, 9, 3, 7, 8],
       [4, 6, 4, 5, 9, 5, 2],
       [9, 7, 5, 3, 1, 0, 2],
       [5, 4, 2, 1, 0, 6, 2]])

In [409]:
X = matrix[:,0:6]
X

array([[8, 2, 1, 8, 4, 2],
       [1, 5, 4, 1, 0, 8],
       [7, 7, 7, 5, 5, 7],
       [2, 5, 1, 4, 5, 6],
       [4, 4, 0, 9, 3, 4],
       [1, 8, 7, 5, 9, 7],
       [6, 3, 0, 9, 3, 7],
       [4, 6, 4, 5, 9, 5],
       [9, 7, 5, 3, 1, 0],
       [5, 4, 2, 1, 0, 6]])

In [410]:
Y = matrix[:,5:6]
Y

array([[2],
       [8],
       [7],
       [6],
       [4],
       [7],
       [7],
       [5],
       [0],
       [6]])

In [411]:
np.savetxt("MCO.CSV",matrix,delimiter=",")

In [412]:
csv=np.loadtxt("MCO.CSV", delimiter=",")
csv

array([[8., 2., 1., 8., 4., 2., 7.],
       [1., 5., 4., 1., 0., 8., 1.],
       [7., 7., 7., 5., 5., 7., 0.],
       [2., 5., 1., 4., 5., 6., 5.],
       [4., 4., 0., 9., 3., 4., 7.],
       [1., 8., 7., 5., 9., 7., 8.],
       [6., 3., 0., 9., 3., 7., 8.],
       [4., 6., 4., 5., 9., 5., 2.],
       [9., 7., 5., 3., 1., 0., 2.],
       [5., 4., 2., 1., 0., 6., 2.]])

In [414]:
MY=csv[:,5:6]
MY

array([[2.],
       [8.],
       [7.],
       [6.],
       [4.],
       [7.],
       [7.],
       [5.],
       [0.],
       [6.]])

In [415]:
MX=csv[:,0:6]
MX

array([[8., 2., 1., 8., 4., 2.],
       [1., 5., 4., 1., 0., 8.],
       [7., 7., 7., 5., 5., 7.],
       [2., 5., 1., 4., 5., 6.],
       [4., 4., 0., 9., 3., 4.],
       [1., 8., 7., 5., 9., 7.],
       [6., 3., 0., 9., 3., 7.],
       [4., 6., 4., 5., 9., 5.],
       [9., 7., 5., 3., 1., 0.],
       [5., 4., 2., 1., 0., 6.]])

In [416]:
XTRANS=MX.T
XTRANS

array([[8., 1., 7., 2., 4., 1., 6., 4., 9., 5.],
       [2., 5., 7., 5., 4., 8., 3., 6., 7., 4.],
       [1., 4., 7., 1., 0., 7., 0., 4., 5., 2.],
       [8., 1., 5., 4., 9., 5., 9., 5., 3., 1.],
       [4., 0., 5., 5., 3., 9., 3., 9., 1., 0.],
       [2., 8., 7., 6., 4., 7., 7., 5., 0., 6.]])

In [418]:
xtransporx=XTRANS@MX
xtransporx

array([[293., 229., 141., 255., 161., 200.],
       [229., 293., 199., 234., 222., 270.],
       [141., 199., 161., 123., 148., 170.],
       [255., 234., 123., 328., 224., 248.],
       [161., 222., 148., 224., 247., 214.],
       [200., 270., 170., 248., 214., 328.]])

In [419]:
beta=np.linalg.inv(xtransporx)@XTRANS@MY
beta

array([[-1.77635684e-15],
       [ 9.88098492e-15],
       [-6.66133815e-15],
       [-1.99840144e-15],
       [-2.22044605e-16],
       [ 1.00000000e+00]])

In [420]:
AnswY=MX@beta
AnswY

array([[2.00000000e+00],
       [8.00000000e+00],
       [7.00000000e+00],
       [6.00000000e+00],
       [4.00000000e+00],
       [7.00000000e+00],
       [7.00000000e+00],
       [5.00000000e+00],
       [1.36557432e-14],
       [6.00000000e+00]])

In [421]:
def estimacionMCO():
    csv=np.loadtxt("MCO.CSV", delimiter=",")
    MY=csv[:,5:6]
    MX=csv[:,0:6]
    XTRANS=MX.T
    xtransporx=XTRANS@MX
    beta=np.linalg.inv(xtransporx)@XTRANS@MY
    AnswY=MX@beta
    return AnswY


In [422]:
estimacionMCO()

array([[2.00000000e+00],
       [8.00000000e+00],
       [7.00000000e+00],
       [6.00000000e+00],
       [4.00000000e+00],
       [7.00000000e+00],
       [7.00000000e+00],
       [5.00000000e+00],
       [1.36557432e-14],
       [6.00000000e+00]])